### ISSUE TITLE
Core Requests/Issues

### ISSUE THREAD

**Issue by WodsonKun** [Aftnet/LibretroRT#26]
Here, you can comment your Core requests and your Core troubles/issues 😁.

**Comment by WodsonKun** [comment]
[Nintendo 64 Core Request]

Will you add a Nintendo 64 core?

And, if you add, will you use Mupen64Plus Core or ParallelN64 Core?

**Comment by albertofustinoni** [comment]
If I can manage to, yeah.

From 16 bit onwards consoles start using 3D, which means Libretro cores for them rely on 3D acceleration. I don't know whether I will manage to get that working, to be honest. PlayStation is about the last thing you can get away with if limited to software rendering.

**Comment by MysteriousHercules** [comment]
A request I have is 16:9 support or widescreen support. I do not how hard it will be but it would be awesome for me because I am not a fan of black bars.

I was wondering though, does Angle have 3d support like n64?

**Comment by MysteriousHercules** [comment]
I guess for core requests, I would want either dosbox, mame, or prboom. I do not think anyone of them requires 3d acceleration. but you know more than I do.

**Comment by WodsonKun** [comment]
@MobWi ported Mupen64Plus to UWP (Win64e10) using ANGLE (If I'm not wrong...)

@MysteriousHercules Yep, ANGLE supports 3D, @perneky used it to make a initial port of PPSSPP to UWP

**Comment by MysteriousHercules** [comment]
well we do not want a small performance, because win64e10 is a very badly designed emulator. Even super Mario 64 has massive slowdown. on that emulator, and other games do not run at all. but you guys know more than I do. I am honestly interested to see how they would port ps2 to xbox one, the only good ps2 emulator is pcsx2. and from what I have been told it is not portable.

**Comment by WodsonKun** [comment]
Hm... Looks like they will port PCSX2 code just into a new UI

**Comment by dominater01** [comment]
ppsspp run great on xbox one what you mean

**Comment by MysteriousHercules** [comment]
does ppsspp uwp use angle?

**Comment by dominater01** [comment]
maybe not idk it doesnt say but if thats what you ment nevermind then

i just thought you we're saying it was slow on xbox one in general

**Comment by MysteriousHercules** [comment]
I think n64 emulator should be possible. but as alberto mentioned, it may mean he will have to re edit some part of his code to use hardware rendering

**Comment by WodsonKun** [comment]
@dominater01 Not the official port, the port made by MobWi (WinPSPe)

@MysteriousHercules Yep, a older version of WinPSPe/PPSSPP used ANGLE

**Comment by perneky** [comment]
ANGLE is not THAT slow. It is used in both Chrome and FF to render WebGL content, and it is even fast enough to render Unreal Engine in a browser.

When it comes to emulation, the Emulator's overhead will be bugger than ANGLE's.

**Comment by MysteriousHercules** [comment]
so is there hope for more 3d advanced emulators on xbox one  like dolphin, ps2, and reicast? or even citra that just released.

**Comment by perneky** [comment]
The problem with publishing on any Windows store (Windows 10 or XB1) is this: https://arstechnica.com/gaming/2017/04/microsoft-formally-bans-emulators-on-xbox-windows-10-download-shops/

Also with PPSSPP they have contacted MS, about publishing it on the store, but the rule here is that you need an approval for that from the platform holder, (so Nintendo or Sony) so that they agree to have that emulator in the Store, which is very unlikely.

**Comment by dominater01** [comment]
we're not trying to publish to the store tho

**Comment by albertofustinoni** [comment]
It is exactly as @pernkey says

As I state in the project's front page, the hope is RetriX should become a good enough product distributed outside the store that people take notice of Windows 10's ability to side load (and hopefully complain loudly should Microsoft ever try to remove side loading).

To do so, however, the installation process needs to be more "install android app" and less "compile from source after setting pic for development", which is the reason I want to do binary distribution with an authenticode certificate.

**Comment by MysteriousHercules** [comment]
I personally want that as well. but until Microsoft changes their mind with emulators, I am perfectly fine with just sideloading retrix with dev mode.  Maybe xbox live creator program will allow people to release emulators on xbox one.


Actually I just remembered something, if you go to the windows store right now, you will see a bunch of zx spectrum and commodore 64 emulators still active despite Microsoft saying  "banned from all windows devices" . This is because these emulators claim to be more "general" than being just "gaming" emulators. I was wondering if we could use a loophole like that to release retrix.

When you think about it, the rule says "Apps that emulate a game system are not allowed on any device family". So couldn't we just say something like retrix is used for educational purposes to teach people about older games. it is not just a gaming emulator, it also has stuff like "rpgmaker, dosbox, commodore 64" etc. 

I know there is more to it than that, but I figured that you guys may have a better idea to use a loophole like that to release the emulator. 

Sorry for the very long post.

**Comment by MysteriousHercules** [comment]
I guess another way would be using Linux, since Microsoft just announced that Linux will officially be supported on xbox one by them.

**Comment by MysteriousHercules** [comment]
here is the link: "https://www.engadget.com/2017/05/11/microsoft-will-offer-3-flavors-of-linux-on-the-windows-store/"

**Comment by wiired24** [comment]
@albertofustinoni  give this a look. It's the tool I've been using to make binary builds for easy sideloading  https://youtu.be/QcKHCcaa1b0

**Comment by albertofustinoni** [comment]
@MysteriousHercules As you yourself said, claiming RetriX is for educational purposes is a loophole, and Microsoft is not that dumb. Best case scenario, it squeezes through initial certification but you can bet it would be taken down the minute it gained any real traction. Also, I already have a bunch of apps on the store and am not going to put my dev account at risk.

Using Linux is not a way to get around the limitation since:

- It's technically impossible to run RetriX on Linux
- Having to download a whole Linux distro to run one program on windows is pointless: at that point just getting Retroarch or something is way easier and takes less space

@wiired24 Making the binary is not the issue: you can do that easily within Visual Studio. The issue is getting that appx to install on PCs that do not have developer mode enabled. Turning developer mode on has security implications for the device.

Even leaving that aside, I want to have signed binary releases so that users can be sure the RetriX appx comes from me and has not been tampered with - I find myself quite often having to run executables for some small utility that I need and crossing my fingers I don't get infected. See [this article](https://noncombatant.org/2014/03/03/downloading-software-safely-is-nearly-impossible/) and [discussion](https://news.ycombinator.com/item?id=9577861) to understand what I mean.

**Comment by dominater01** [comment]
hey alberto can you implement a debug list to retrix so we can see whats wrong on the xbox one

**Comment by MysteriousHercules** [comment]
That is a fair point, As I said, until Microsoft change their views on emulators, I am perfectly fine with resorting to xbox dev mode to sideload apps. Maybe xbox live creator program will allow emulators on the store.

**Comment by WodsonKun** [comment]
@dominater01 I suggested to @albertofustinoni on https://github.com/Aftnet/LibretroRT/issues/27 to add HockeyApp to RetriX...

**Comment by dominater01** [comment]
@WodsonKun i see that i just asked here aswell because i dont know if he's reading the other one as much as this one

**Comment by albertofustinoni** [comment]
@dominater01 @WodsonKun HockeyApp is something I'm going to look into, although I think it will have to wait for a bit. Right now the codebase is changing quite a bit and things will break.

**Comment by MysteriousHercules** [comment]
I assume you already know this, but one thing I learnt when testing and editing ppsspp on xbox one, is that crashes can be created due to exceeding the 1 gb processing limit.

**Comment by dominater01** [comment]
since this is a request thread i would like to have turbografx 16 and cd, virtual boy, 32x, and neo geo pocket/color and maybe throw some atari 2600 5200 7800 as well

**Comment by WodsonKun** [comment]
@albertofustinoni I'd even offer my Xbox One for RetriX testing... But, I do not have a developer account 😪

**Comment by MysteriousHercules** [comment]
@WodsonKun if you are willing to still donate an xbox one to @albertofustinoni, he could use the donation money from his fundme page to get a dev account for himself.

**Comment by WodsonKun** [comment]
@MysteriousHercules I'm 14-years old... I do not have money... 😔

**Comment by WodsonKun** [comment]
And I not would go donate my Xbox... I would test RetriX and send some performance reports

**Comment by MysteriousHercules** [comment]
@WodsonKun  oh sorry I understood you wrong. I thought you were saying you do not mind donating an xbox one. and that is why I was saying that he could use the money from the fundme page to get a dev account

**Comment by dominater01** [comment]
would like to request turbo grafx 16 and CD support

**Comment by wiired24** [comment]
@albertofustinoni  If it's not too much trouble could you try swapping out the "Beetle PSX" PS1 Core for PCSX-ReARMed. That's what winpse10 uses and it runs pretty solid in terms to performance.

Here is the official libretro repo
https://github.com/libretro/pcsx_rearmed

**Comment by Albinoman887** [comment]
looks like with the "refactoring" commit change the Parallel64 coreinforeads test passes.. could you try adding it to gui now?

**Comment by WodsonKun** [comment]
@albertofustinoni Can you add Dolphin core on RetriX? I want play some GC games...

**Comment by dominater01** [comment]
@WodsonKun he sed dolphin is gonna have to wait since its experamental even on retroarch

**Comment by WodsonKun** [comment]
@dominater01 Experimental, but runs good on high-end PCs...
A Xbox One, technically, it's a high-end PC, but, in a console form.

**Comment by dominater01** [comment]
this is what he sed word for word

Dolphin is going to be much harder, since it requires GPU acceleration and even the Libretro guys consider their port experimental. As much as I want it, it will have to wait.

**Comment by albertofustinoni** [comment]
@Albinoman887 That test has always passed, no relevant changes were made in that commit. You should probably merge from a current version of the RetriX repo and add it to your own builds yourself. It is a single line of code now -look in EmulationSetvice.cs

@WodsonKun Xbox One is anythimg but a high end PC, especially with regards to CPU, which is something emulators need more than normal games.

Dolphin is a hard core to add: it needs GPU acceleration in addition to what has been mentioned above. As much as I want it myself it *will* have to wait

**Comment by WodsonKun** [comment]
@albertofustinoni

MelonDS runs laggy on Xbox One... Can you change to DeSmuME core?

**Comment by Maisso89** [comment]
Alberto, could you change the Psx core on xbox? The current one runs extremely bad. Thanks and keep up the great work!

**Comment by TheExpertNoob** [comment]
[all cores request]
game genie and gameshark support would be cool.
