### ISSUE TITLE
Core Issues on Xbox One

### ISSUE THREAD

**Issue by dominater01** [Aftnet/LibretroRT#27]
the sega genesis and gba both crash on me after alittle bit of gameplay (random times)

sega master system, gamegear and sg-1000 give black screens

and gameboy and gameboy color crash after game intro

gba games format saves in game every launch

**Comment by albertofustinoni** [comment]
Could you tell me which games you are running that are causing trouble?

**Comment by MysteriousHercules** [comment]
For me, I had sonic advance 1 crash multiple times in the game boy advance emulator, and I had mega man x2 crash on the snes emulator.

**Comment by wiired24** [comment]
Super Mario world on the SNES Emulator crashes occasionally as well

**Comment by dominater01** [comment]
im using the goodroms set btw 

games like vectorman on genesis crash super mario advance (the 3rd one on the nes) on gba

games like pokemon blue for example crash on gb after intro

**Comment by albertofustinoni** [comment]
It's worse than I though... so far I had persistent issues only with Game Boy emulation.

Thing is, I am using the cores source code as is: unless I am compiling it wrong (which could be, as I basically have to reverse engineer the build process since Libretro developers use Linux as their main platform), you need to talk to the core maintainers themselves.

It may also be that the issues are Xbox specific, I have no way to tell right now.

Between this and the need to finish the Xbox UI, I think I'll need to raise some funds to get myself an Xbox One (and a code signing certificate allow people to use RetriX without having to compile it themselves). Would you be willing to help?

**Comment by MysteriousHercules** [comment]
we could share your funding link on gbatemp, this should get you some funding help. other than that, we could be your testers until then. other than that, I do not know how else I could help.

**Comment by MysteriousHercules** [comment]
how do we contact the core maintainers? and what should we tell them?  and to be fair, your emulator is very well playable. it just crashes occasionally. In my opinion just focus on adding some cores for now.

**Comment by dominater01** [comment]
can you just implement a debug list for crashes etc. then i could show you what the problem is 

im no developer so im not gonna be much help but i have alot of time on my hands to help test when needed

**Comment by MysteriousHercules** [comment]
I am a uwp developer in training, and I understand your code a little. for example, I was able to change your controls after downloading your code, so I could try and help with the UI if you need to. if you need something coding based, I could try as well.

**Comment by wiired24** [comment]
@albertofustinoni  set up a fundraising campaign man. I can tell you right now myself and many others will glady donate to you to help you out. We believe in what you are doing and greatly appriciate the work you are putting into this project on your own free time. I'll even embed a link to the fundraiser both on the official page where we link to Retrix on gbatemp as well as on my profile signature. I'll help as much as I possibly can because I believe Retrix is something that is a great benefit to this community and the world.

**Comment by WodsonKun** [comment]
@albertofustinoni I have a Xbox One, but, not a dev account...

**Comment by wiired24** [comment]
Also to be quite honest @albertofustinoni  I have an Xbox One with developer mode. I've said before that I don't care to test for you. And as far as code signing certificates go I have a .APPX packaging tool that I use for packaging UWP Applications into .APPX packages. I could do builds for you. In fact I already have done quite a few builds. So honestly you don't really need to spend money on either of those things.

**Comment by WodsonKun** [comment]
Implement HockeyApp on RetriX! You will be able to see app's errors and some crash reasons...

**Comment by albertofustinoni** [comment]
@WodsonKun I'm going to have to look into that when I get some time. HockeyApp could be a good way of getting data from other people.

**Comment by dominater01** [comment]
all cores now work on xbox one but they still have crashing issues

**Comment by albertofustinoni** [comment]
I am starting to believe this is due to Xbox One being x64.
To develop, I am mostly running in x86 because and I am not seeing (as many) crashes there.

I suspect I may be doing something wrong when compiling (wrong pre-processor directive  perhaps?), will have to look into it more when I have a chance.

**Comment by MysteriousHercules** [comment]
Is there something I can do to help you compile. I have x64 pc and xbox one with dev account

**Comment by MysteriousHercules** [comment]
I mean it makes sense, if it doesn't crash on pc, then It is not a coding issue. It is either an issue with dev mode or compiling

**Comment by WodsonKun** [comment]
http://www.xb1emu.com/uncategorized/get-a-free-developer-account/

For the people that don't have a Dev Account... I finally got one!

**Comment by WodsonKun** [comment]
Look at it @albertofustinoni
Now you can have your Developer Account by free! But, get hurry... It's for a limited time...

**Comment by albertofustinoni** [comment]
Is this the same developer account as the one needed to publish apps on the Windows Store?

If so, I'm good: I already have [several apps there](https://www.aftnet.net/)

**Comment by dominater01** [comment]
thats for dev mode on xbox one so you can sideload apps like us so you dont have to pay 19$

**Comment by albertofustinoni** [comment]
Ok, if it's a different account I need to get in on that.

**Comment by WodsonKun** [comment]
I finally tested RetriX on my Xbox... @albertofustinoni Man, you need add a option to get back into RetriX's UI... About performance, everything runs ok... I not tested Sega CD

**Comment by albertofustinoni** [comment]
I am painfully aware, believe me...

Lately I haven't had a chance to go on working on the UI because of trying to get PlayStation working.

Hopefully I'll get to it soon.

**Comment by dominater01** [comment]
are you releasing these builds as a dubug or retail?

**Comment by albertofustinoni** [comment]
You mean Release? Yes, the binary builds I post are all release

**Comment by dominater01** [comment]
ok just making sure because wiired24 noticed better compatibility with the ppsspp emulator when changed to retail build instead of debug but wiired24 just checked and its the same so nevermind

**Comment by dominater01** [comment]
this seems to finally be fixed with sherushaku's fix from gbatemp

**Comment by albertofustinoni** [comment]
Yeah, closing this one now
