### ISSUE TITLE
Linux Port

### ISSUE THREAD

**Issue by RobLoach** [Aftnet/LibretroRT#31]
Very nicely done on the new frontend! There aren't many RetroArch frontend alternatives, so thanks for filling in that need.

Interested in trying out a Linux Port. Have any tips?

**Comment by albertofustinoni** [comment]
I feel this would be an uphill struggle.

I am developing with an eye to cross platform portability, but that would be via Xamarin - most of the UI logic is contained in he Retrix.Shared assembly, which is .net Standard 1.4 (so supported on iOS, Android and MacOS). I do not know what frameworks for C# on Linux support that.

Then you'd have to hook up the viewmodels to whatever UI framework you'd use (not difficult, just a bit tedious, but still better than starting from scratch), since there's no Xamarin Formson Linux.

And then you'd have to write the rest of the code base to work on Linux and interop with the shared assembly mentioned above. Doable, but at this point you may feel like it's not worth bothering with.
